export const ALLURECTL_PID = 'ALLURECTL_PID'
export const ENV_ALLURE_ENDPOINT = 'ALLURE_ENDPOINT'
export const ENV_ALLURE_TOKEN = 'ALLURE_TOKEN'
export const ENV_ALLURE_PROJECT_ID = 'ALLURE_PROJECT_ID'
